plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

sourceCompatibility = '17'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	// spring data jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// mysql connector
	implementation 'com.mysql:mysql-connector-j'
	//security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	//validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	//email 寄送
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	// JWT 核心 API，必加
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	// 實作（用來產生/驗證 token）
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	// 用 Jackson 來支援 JSON處理 解析
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
	
	//spring cache //暫存資料
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	//caffeine cache
	implementation 'com.github.ben-manes.caffeine:caffeine:3.2.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
