spring.application.name=daily

 #系統的預設 port 是 8080，透過下一行的設定可以改成 8083
#server.port=8083
# 設定資料庫連接
# 3306是連接 mysql 的 port；p12 是要連接的資料庫名稱
# rewriteBatchedStatements=true: 可以批次新增
spring.datasource.url=jdbc:mysql://localhost:3306/diary?serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

